### PR TITLE
NXP-21384: release nuxeo-groups-rights-audit for 9.10

### PR DESCRIPTION
**Pull request by driverpt**

### CODE REVIEW

**Comment by jcarsique** [comment]
:+1:

**Comment by pgmillon** [comment]
Branch 1.9_9.10 doesn't exist in https://github.com/nuxeo/marketplace-groups-rights-audit

**Comment by driverpt** [comment]
@pgmillon , i know :)

**Comment by pgmillon** [comment]
Ok sorry I haven't noticed https://github.com/nuxeo/marketplace-groups-rights-audit/pull/1

**Comment by pgmillon** [comment]
👍

**Pull request merged**
