### PR TITLE
Feature  NXBT-1513 CI/CI docker hosts

### PR DESCRIPTION
**Pull request by jcarsique**
Put static slaves maintenance under CI/CD

### CODE REVIEW

**Comment by jcarsique** [comment]
TODO: 
- complete https://github.com/nuxeo/integration-scripts/blob/master/README.md#qa-ovh-maintenance
- cleanup headers, format
- possible factorization?
- fix consistency

**Comment by jcarsique** [comment]
:+1:

**Comment by jcarsique** [comment]
please ignore manual/ folder, it's a set of legacy scripts stored for the record

**Comment by alexistimic** [comment]
:+1:

**Comment by nxmatic** [comment]
:+1:

**Pull request merged**
